-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 10, 2026 at 07:22 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ayurveda_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `diseases`
--

CREATE TABLE `diseases` (
  `id` int(11) NOT NULL,
  `disease_name` varchar(100) NOT NULL,
  `causes` text NOT NULL,
  `symptoms` text NOT NULL,
  `allopathy_medicine` text NOT NULL,
  `allopathy_image` varchar(255) NOT NULL,
  `traditional_medicine` text NOT NULL,
  `traditional_image` varchar(255) NOT NULL,
  `preparation_usage` text NOT NULL,
  `why_traditional` text NOT NULL,
  `side_effects` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `diseases`
--

INSERT INTO `diseases` (`id`, `disease_name`, `causes`, `symptoms`, `allopathy_medicine`, `allopathy_image`, `traditional_medicine`, `traditional_image`, `preparation_usage`, `why_traditional`, `side_effects`) VALUES
(1, 'Asthma', 'Genetic predisposition and Exposure to allergens such as dust miles, pollen, pet dander, and smoke. Air pollution, respiratory infections, cold air, and occupational chemical exposure also trigger airway inflammation and leads to asthma.', 'Shortness of breath\r\n\r\nwheezing(means a whistling sound during breathing)\r\n\r\nchest tightness \r\n\r\npersistent coughing. ', 'Salbutamol – a bronchodilator that relaxes airway muscles and provides quick relief from asthma attacks. \r\n\r\nBudesonide – a corticosteroid inhaler that reduces airway inflammation. \r\n\r\nMontelukast – an anti-allergic medicine that prevents asthma sympt', 'Asthama_allopathy.jpeg', 'Common Name: Malabar Nut\r\nSanskrit Name: Vasaka \r\nScientific Name: Adhatoda vasica \r\n', 'Asthama_trad_medicinal.jpeg', 'The leaves of vasaka are used in ayurvedic medicine. Fresh leaves are washed and boiled in water to prepare a herbal decoction. The decoction is filtered and consumed once or twice daily. ', 'Traditional medicines use natural plant compounds that supports long term respiratory health. \r\nThey help strengthen lung function, improves immunity and reduces inflammation without chemicals. ', 'Allopathy medicine may cause side effects like trembling, nervousness, increased heart rate, headache, dizziness due to receptor stimultion. Frequent use may lead to throat irritation, hoarseness, fatigue.\r\n\r\nExcessive amount of ayurvedic medicine causes mild stomach irritation.'),
(2, 'Ear Pain ', 'Ear pain occurs due to inflammation or infection in the ear.bacterial or viral infection that leads to otitis media.Ear pain also causes due to accumulation of earwax in the ear canal,sinus infections increase pressure in the ear or injury to the ear canal or eardrum. ', 'Sharp or dull pain inside the ear\r\n\r\nDifficulty hearing\r\n\r\nFever\r\n\r\nHeadache\r\n\r\nFeeling pressure in the ear.', 'Ibuprofen – an anti-inflammatory medicine used to relieve pain. \r\n\r\nAntibiotic ear drops ', 'earpain_allopathy.jpeg', 'Common Name: Tulasi\r\nSanskrit name: Vrndavani\r\nScientific name: Ocimum sanctum\r\n', 'earpain_traditional.jpeg', 'Fresh leaves are crushed to extract juice, which is slightly warmed and two or three drops are placed in the affected ear. The antibacterial and anti-inflammatory properties of tulsi helps reduce infection and relieve pain.', 'Herbal remedies like tulsi are natural, affordable and less side effects compared to allopathy medicine. They fight with infection and improve immunity without excessive use of synthetic chemicals. ', 'Allopathy medicine(Ciprofloxacin) may cause mild burning or stinging right after application, along with itching inside the ear. They can also lead to ear discomfort, irritation, temporary dizziness.\r\n\r\nExcess use of ayurvedic medicine causes mild stomach irritation.'),
(3, 'Diabetes', 'Diabetes is a metabolic disorder caused by high blood pressure glucose levels due to insufficient insulin production or insulin resistance. There are two types of diabetes they are: \r\nType-1 diabetes: \r\nCauses: \r\nType -1 diabetes occurs when the immune system destroys the insulin means producing beta \r\ncells in the pancreas. Pancreas stops producing insulin. Without insulin glucose cannot enters \r\ninto the body cells and accumulates in the bloodstream. \r\nType-2 diabetes: \r\nCauses: \r\nType-2 diabetes occurs due to insulin resistance, where body cells do not respond properly to insulin. The pancreas produces insulin but the body cannot use it effectively. major factors \r\nleads to type-2 diabetes includes: excessive body weight(obesity), lack of physical activity, unhealthy diet, increasing age which reduces the efficiency of insulin usage in the body. \r\n', 'Frequent urination\r\n\r\nExcessive thirst\r\n\r\nFatigue\r\n\r\nBlurred vision\r\n\r\nSlow wound healing\r\n\r\nUnexplained weight loss\r\n\r\nLong term uncontrolled diabetes can damage nerves, kidney eyes and blood vessels. ', 'Metformin-reduces glucose production int the liver.\r\n\r\nGlimepiride-stimulates insulin release from the pancreas.\r\n \r\nInsulin injections-used when the body cannot produce enough insulin.', 'diabetes_allopathy.jpeg', 'Common name: Jamun/ Black plum\r\nSanskrit name: Jambuh \r\nScientific name: Syzygium Cumini\r\n ', 'diabetes_traditional.jpeg', 'Jamun seeds are widely used in ayurveda to manage diabetes. The seeds are collected from ripe fruits, dried in sunlight, and ground into a fine powder. One teaspoon of the powder is mixed with water and consumed daily.', 'Herbal remedies support natural blood sugar regulation, improves digestion and strengthen metabolism. ', 'Allopathy medicine causes nausea, diarrhea, abdominal discomfort, Loss of appetite.\r\n\r\nExcess intake of Traditional medicine causes low blood sugar and dizziness.'),
(4, 'Thyroid ', 'Thyroid disorders occur due to abnormal production of thyroid hormones by the thyroid gland and produces insufficient hormones due to autoimmune destruction of thyroid tissue. \r\nIodine deficiency also affects thyroid hormone production. ', 'Weight changes\r\n\r\nFatigue\r\n\r\nHair loss\r\n\r\nIrregular heartbeat\r\n\r\nDifficulty concentrating\r\n\r\nAffects metabolism and body temperature regulation. ', 'Levothyroxine-a (synthetic thyroid hormone used to treat hypothyroidism). ', 'Thyroid_allopathy.jpeg', 'Common name: Carum Carvi\r\nSanskrit name: Krishna Jiraka \r\nScientific name: Nigella sativa', 'Thyroid_medicinal.jpeg', 'The seeds of nigella sativa are consumed to support metabolic and hormonal balance. The seeds are powdered and mixed with honey or warm water. One teaspoon is taken daily. ', 'Traditional medicine supports natural hormone balance and improves overall metabolism. \r\nAlso provides antioxidants that protect body cells.', 'Allopathy medicine causes increased heart rate, nervousness or anxiety due to increased metabolism, excessive sweating, heat intolerance, difficulty in sleeping.\r\n\r\nExcessive intake of traditional medicine causes digestive discomfort.'),
(5, 'Diarrhea ', 'Diarrhea occurs due to infection or irritation in the gastrointestinal tract, bacterial, viral, or parasitic infection through contaminated food or water. These infections increase intestinal secretion and decrease water absorption. \r\n', 'Frequent watery stools\r\n\r\nAbdominal cramps\r\n\r\nDehydration\r\n\r\nNausea\r\n\r\nWeakness\r\n\r\nLoss of appetite.', 'Oral Rehydration Salts (ORS): prevents dehydration by replacing lost fluids and electrolytes.\r\n \r\nLoperamide: reduces intestinal movement and controls diarrhea.', 'diarrhea_allopathy.jpeg', 'Common Name: Bhandi\r\nSanskrit name: Bhandira \r\nScientific name: Clerodendrum Infortunatum ', 'diarrhea_traditional.jpeg', 'Leaves of Clerodendrum infortunatum  are used in traditional medicine for digestive \r\ndisorders. The leaves are boiled in water to prepare a herbal decoction, which is consumed in small quantities twice daily. ', 'Traditional medicines help restore digestive balance naturally and improves gut health without chemical drugs. ', 'Allopathy medicine may cause constipation, dizziness, abdominal cramps, dry mouth, fatigue.\r\n\r\nExcess consumption of traditional medicine causes mild stomach irritation. \r\n'),
(6, 'Acne', 'Acne is mainly caused by hormonal changes during puberty. It can also occur due to excess oil (sebum) production in the skin. Bacterial infection in the skin pores can also lead to acne. The use of oily cosmetics and poor skin hygiene may increase the chances of developing pimples.', 'The common symptoms of acne include pimples on the face, chest, or back. Red inflamed bumps may appear on the skin. Whiteheads or blackheads are also common signs. Some pimples may be painful or filled with pus.', 'Benzoyl peroxide cream is used to kill bacteria on the skin and reduce pimples and inflammation. \r\nSalicylic acid cream helps remove dead skin cells and opens clogged pores. Antibiotic creams are used to control bacterial infection that causes acne.', 'Acne_allopathy.jpg', 'Common name: Turmeric\r\nSanskrit name: Haridra\r\nScientific name: Curcuma longa\r\n\r\n', 'Turmeric.jpg', 'Turmeric powder can be mixed with honey or rose water to make a paste. This paste is applied to the pimples and left for about 15–20 minutes. After that, it should be washed with lukewarm water.', 'Traditional medicines are preferred because they are made from natural ingredients that are gentle on the skin. They usually cause fewer side effects and help improve the skin naturally over time.', 'Allopathy medicines may sometimes cause skin dryness, redness, or irritation. Traditional medicines usually have very few side effects, but in rare cases they may cause a mild skin allergy.\r\n'),
(7, 'Dandruff', 'Dandruff can occur due to a dry scalp. It may also be caused by fungal infection on the scalp. Poor hair hygiene and excess oil on the scalp can also lead to dandruff.', 'The symptoms of dandruff include white flakes on the scalp and shoulders. People may experience itching on the scalp. The scalp skin may also become dry and irritated.\r\n', 'Ketoconazole shampoo is used to kill the fungus that causes dandruff on the scalp. Selenium sulfide shampoo helps slow down the growth of scalp skin cells and reduces dandruff flakes.\r\n', 'dandruff.jpeg', 'Common name: Amla\r\nSanskrit name: Amalaki\r\nScientific name: Phyllanthus emblica\r\n', 'dandruff_trad.jpg', 'Amla powder can be mixed with water or coconut oil to form a paste. The paste is applied to the scalp and left for about 30 minutes. After that, the hair should be washed with water or mild shampoo.', 'Traditional medicine nourishes the scalp naturally and improves hair strength. It also reduces the use of chemical products on the scalp.', 'Allopathy medicines may sometimes cause scalp irritation or dryness. \r\nTraditional medicines usually have minimal side effects and are generally safe for regular use.'),
(8, 'Skin Rashes and Itching', 'Skin rashes and itching may be caused by allergic reactions. They can also occur due to insect bites or heat rash. In some cases, skin infections may also cause rashes and irritation.', 'The symptoms include red patches on the skin and itching. Some people may also feel a burning sensation. In certain cases, swelling may occur on the affected skin.', 'Hydrocortisone cream is used to reduce inflammation, redness, and itching on the skin. Calamine lotion helps soothe irritated skin and provides relief from itching.', 'skin_allopathy.jpg', 'Common Name:Neem\r\nSanskrit name: Nimba\r\nScientific name: Azadirachta indica\r\n\r\n', 'skin_trad.jpg', 'Fresh neem leaves can be ground into a paste. This paste is applied to the affected area of the skin and left for about 20 minutes before washing with water.', 'Traditional medicine helps purify the skin naturally and promotes long-term healing. It also reduces the frequent use of chemical creams on the skin.', 'Allopathy medicines may sometimes cause burning, dryness, or irritation on sensitive skin. \r\nTraditional medicines are generally safe but may rarely cause mild skin allergy.'),
(9, 'Fungal Infection', 'Fungal infection usually occurs when the skin remains moist and sweaty for a long time. Poor hygiene and sharing towels or clothes with infected people can spread the infection. Weak immunity can also increase the risk of fungal infections.', 'Common symptoms include red circular rashes on the skin. The affected area may itch continuously. The skin may become scaly and may also start peeling.', 'Clotrimazole cream is used to kill fungi and treat fungal skin infections. Ketoconazole cream helps stop the growth of fungi and reduces itching and redness.', 'fungal_allopathy.jpg', 'Common name:Turmeric\r\nSanskrit name: Haridra\r\nScientific name: Curcuma longa\r\n', 'fungal_trad.jpg', 'Turmeric powder can be mixed with coconut oil to make a paste. This mixture is applied to the infected area and left for about 20–30 minutes before washing.', 'Traditional medicine provides a natural antifungal treatment that is easily available and affordable. It is also safer for long-term use.', 'Allopathy medicines may sometimes cause skin irritation or redness. \r\nTraditional medicines rarely cause side effects but may cause mild allergy in some individuals.'),
(10, 'Sneezing (Allergic Rhinitis)', 'Sneezing may occur due to dust allergy or pollen allergy. Cold weather and viral infections can also trigger allergic rhinitis.', 'Common symptoms include frequent sneezing and a runny nose. People may also experience nasal congestion and itching in the nose.', 'Cetirizine tablets are used to reduce allergy symptoms such as sneezing, runny nose, and itching. Loratadine tablets help block histamine in the body and control allergic reactions.', 'sneezing_allopathy.jpg', 'Common name:Tulsi\r\nSanskrit name: Tulasi\r\nScientific name: Ocimum tenuiflorum\r\n', 'sneezing_trad.jpg', 'Tulsi leaves can be boiled in water to make herbal tea. Drinking this warm tulsi tea once or twice a day helps relieve sneezing and cold symptoms. Fresh tulsi leaves can also be chewed daily.\r\n\r\n', 'Traditional medicine helps improve immunity and provides a natural way to treat respiratory problems. It usually does not cause drowsiness or other common side effects.', 'Allopathy medicines may sometimes cause drowsiness or tiredness. \r\nTraditional medicines usually do not cause major side effects and are considered safe when used properly.'),
(11, 'Menstrual Pain', 'The main cause is high levels of prostaglandins, which make the uterus contract strongly, reducing blood flow. Other causes include endometriosis, fibroids, or pelvic inflammatory disease.', 'Throbbing, cramping pain in the lower abdomen, nausea, vomiting, diarrhea, headache, fatigue, and lower back pain.', 'Ibuprofen, Naproxen, and Mefenamic Acid + Dicyclomine are commonly used to reduce pain and inflammation.', 'menstrual_allopathy.jpg', 'Common name: Ashoka, Shatavari, Lodhra, Ginger\nScientific names: Saraca asoca, Asparagus racemosus, Symplocos racemosa, Zingiber officinale', 'menstrual_trad.jpg', 'Herbal formulations like Ashokarishta and Dashamoola are used. Herbs are consumed as decoctions or powders to reduce cramps and balance hormones.', 'Traditional medicine treats root causes like Vata imbalance, has fewer side effects, and supports long-term reproductive health.', 'Allopathy may cause stomach upset, nausea, dizziness. Excess traditional use may cause mild reactions if not properly guided.'),
(12, 'Motion Sickness', 'Caused by sensory mismatch between eyes, inner ear, and body movement. Common during travel or screen use in moving vehicles.', 'Nausea, vomiting, dizziness, cold sweats, headache, fatigue, and drowsiness.', 'Dimenhydrinate, Meclizine, Scopolamine, and Promethazine are used to control symptoms.', 'motion_allopathy.jpg', 'Common name: Ginger, Cardamom, Lemon\nScientific names: Zingiber officinale, Elettaria cardamomum, Citrus limon', 'motion_trad.jpg', 'Ginger tea, lemon juice, and herbal powders like Eladi Churna are used to reduce nausea naturally.', 'Traditional remedies are natural, avoid drowsiness, and treat root imbalance without harsh chemicals.', 'Allopathy may cause drowsiness, dry mouth, blurred vision. Traditional remedies are mostly safe but excess may cause mild heartburn.'),
(13, 'Leg Pain', 'Caused by muscle cramps, injuries, poor blood flow, nerve issues, arthritis, or deficiencies.', 'Dull or sharp pain, swelling, stiffness, numbness, tingling, and heaviness in legs.', 'Ibuprofen, Diclofenac, Acetaminophen, muscle relaxants, and nerve pain medicines are commonly used.', 'legpain_allopathy.jpg', 'Common name: Ashwagandha, Nirgundi, Ginger\nScientific names: Withania somnifera, Vitex negundo, Zingiber officinale', 'legpain_trad.jpg', 'Oils like Mahanarayana Tailam are used for massage. Herbal tablets like Yogaraja Guggulu reduce inflammation.', 'Traditional medicine strengthens muscles, improves flexibility, and provides long-term healing with fewer side effects.', 'Allopathy may cause ulcers, kidney issues if overused. Traditional medicine may cause minor irritation if misused.'),
(14, 'Bloating', 'Caused by gas buildup, constipation, or hormonal changes affecting digestion.', 'Abdominal fullness, swelling, gas, burping, pain, and bowel changes.', 'Simethicone and digestive enzyme supplements like Lactase are commonly used.', 'bloating_allopathy.jpg', 'Common name: Peppermint, Ginger, Fennel\nScientific names: Mentha piperita, Zingiber officinale, Foeniculum vulgare', 'bloating_trad.jpg', 'Herbal teas like peppermint, ginger, and fennel are consumed to improve digestion and reduce gas.', 'Traditional medicine focuses on improving digestion and treating root causes naturally.', 'Allopathy is safe but temporary. Excess herbal use may cause mild discomfort.'),
(17, 'Common Cold', 'Common cold is caused by viral infection (rhinovirus), weather changes, weak immune system, close contact with infected people, and touching nose, mouth, or eyes without washing hands.', 'Runny or blocked nose, sneezing, sore throat, mild fever, cough, headache, and body weakness.', 'Paracetamol, Ibuprofen, and Cetirizine are commonly used to reduce fever, runny nose, and body pain.', 'commoncold_allopathy.jpg', 'Common name: Black Pepper\nSanskrit name: Maricha\nScientific name: Piper nigrum', 'commoncold_traditional.jpg', 'Mix half teaspoon of black pepper powder with honey or boiled milk to clear nasal passages and reduce kapha.', 'Black pepper helps the body naturally fight cold, improves digestion, increases body warmth, clears mucus, has fewer side effects, and boosts immunity.', 'Long-term use of allopathic medicine may cause stomach problems, kidney issues, allergic reactions, dizziness, headache, and increased heart risk.'),
(18, 'Fever', 'Fever is caused by viral infections, bacterial infections, inflammation in the body, heat exhaustion, or dehydration.', 'High body temperature, chills, sweating, headache, body aches, weakness, loss of appetite, tiredness, and dehydration.', 'Aspirin and Acetaminophen are commonly used to reduce fever.', 'fever_allopathy.jpg', 'Common name: Guduchi\nScientific name: Tinospora cordifolia', 'fever_traditional.jpg', 'Take a 6-inch fresh Guduchi stem, crush it, boil in four parts water until reduced to one part, and drink 20 ml twice daily.', 'Guduchi boosts immunity, has fewer side effects, and provides long-term health benefits.', 'Long-term use of aspirin may cause stomach irritation, ulcers, bleeding, and allergic reactions.'),
(19, 'Stomach Ache', 'Stomach ache is caused by indigestion, gas, bloating, constipation, food poisoning, stomach infection, and gastritis.', 'Abdominal pain, bloating, nausea, vomiting, loss of appetite, and burning sensation in the stomach.', 'Antacids, Omeprazole, Dicycloverine, and Simethicone are used to treat stomach pain.', 'stomachache_allopathy.jpg', 'Common name: Hingu\nScientific name: Asafoetida', 'stomachache_traditional.jpg', 'Dissolve a pinch of roasted hingu in warm water or apply as paste over the navel. It can also be added to food.', 'Hingu helps digestion naturally and has fewer side effects compared to allopathic medicine.', 'Allopathic medicines may cause constipation, diarrhea, nausea, vomiting, stomach cramps, mineral imbalance, and kidney problems.'),
(20, 'Migraine', 'Migraine is caused by stress, hormonal changes, lack of sleep, certain foods, bright lights, loud sounds, dehydration, and weather changes.', 'Severe throbbing headache, nausea, vomiting, sensitivity to light and sound, blurred vision, and dizziness.', 'Sumatriptan, Naproxen, Paracetamol, and Aspirin are used for migraine relief.', 'migraine_allopathy.jpg', 'Common name: Ghee\nSanskrit name: Ghrita', 'migraine_traditional.jpg', 'Administer 2 drops of lukewarm cow ghee into each nostril on an empty stomach.', 'Ghee supports brain and nervous system health, balances body functions, and has fewer side effects than allopathic medicines.', 'Allopathic medicines may cause dizziness, tingling, nausea, redness of skin, chest tightness, and increased blood pressure.'),
(21, 'Vomiting', 'Vomiting is caused by food poisoning, stomach infection, indigestion, motion sickness, migraine, and high fever.', 'Nausea, stomach discomfort, loss of appetite, sweating, weakness, dehydration, and dizziness.', 'Ondansetron, Domperidone, Metoclopramide, and Promethazine are commonly used.', 'vomiting_allopathy.jpg', 'Common name: Cardamom\nSanskrit name: Ela\nScientific name: Elettaria cardamomum', 'vomiting_traditional.jpg', 'Mix finely ground cardamom seed powder with honey and lick slowly.', 'Cardamom relieves nausea naturally, helps digestion, reduces stomach discomfort, and usually has fewer side effects.', 'Allopathic medicines may cause stomach problems, allergic reactions, liver damage, kidney problems, stomach bleeding, and drug dependence.');

-- --------------------------------------------------------

--
-- Table structure for table `medicinal_plants`
--

CREATE TABLE `medicinal_plants` (
  `id` int(11) NOT NULL,
  `plant_name` varchar(100) NOT NULL,
  `sanskrit_name` varchar(100) DEFAULT NULL,
  `scientific_name` varchar(150) DEFAULT NULL,
  `other_names` varchar(200) DEFAULT NULL,
  `benefits` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `medicinal_plants`
--

INSERT INTO `medicinal_plants` (`id`, `plant_name`, `sanskrit_name`, `scientific_name`, `other_names`, `benefits`, `image`) VALUES
(1, 'Snakeroot', 'Śālapaṣpā', 'Rauvolfia serpentina', 'Devil pepper, Serpentine wood, Sarpagandha, Chandrika, and snakewood', 'Widely used for balancing Vāta disorders such as:\r\nFemale reproductive disorders,\r\nGeneral body weakness and fatigue,\r\nVāta-related diseases like joint pain.\r\nIt balances Vāta and Pitta, used for \r\nStrengthening (Balya), and also\r\nAnti-inflammatory.\r\nIt is important because it is a key ingredient in many classical Ayurvedic formulations for rejuvenation and strength.', 'Rauvolfia_serpentina.jpg\r\n'),
(2, 'Sweet Flag', 'Vacā', 'Acorus calamus', NULL, 'It is a powerful herb used in neurological and digestive disorders. It is used to \r\nImproves speech and memory,Mental disorders (Unmāda), Digestive stimulant.\r\nIt also enhances brain function,Removes toxins (Āma), Stimulates digestion.\r\nIt is widely used in children for speech development and cognitive improvement.', 'Acorus_calamus.jpg'),
(3, 'Common juniper', 'Hapuṣā', 'Juniperus communis', 'Juniperberry,Juniper', 'Hapuṣā is an aromatic plant known for its strong digestive and urinary benefits.It is used for Urinary disorders, Digestive problems, Gas and bloating.It is also\r\nDiuretic (increases urine flow), Carminative, Detoxifying. It\r\nhelps cleanse the urinary system and improves metabolism.', 'Juniperus_communis_fruits.jpg'),
(4, 'False black pepper', 'Kṛmihā / Viḍaṅga ', 'Embelia ribes', 'White-flowered Embelia, Vidanga, Vavding, Nainidang', 'It is used for removing intestinal worms,\r\ncuring skin diseases, digestive cleansing,\r\nStrong anthelmintic (kills worms),\r\nDetoxifying, Improves digestion\r\nIt is very effective in children and adults for parasite infections.', 'Embelia_ribes.jpg'),
(5, 'Indrayava', 'Kutaja tree', 'Holarrhena pubescens ', 'Kalinga, Vatsaka, Indrabīja, Holarrhena antidysenterica (Latin name)', ' It is highly effective for chronic digestive disorders. It is also used for \r\nChronic diarrhea ,Fever with loose motions, Digestive issues.It has Cooling, Anti-diarrheal, Strengthens intestines properties. it is also used when diarrhea becomes long-term or severe.', 'Holarrhena_pubescens.jpg'),
(6, 'Hingu', 'Hingu', 'Ferula asafoetida', 'The other names for hingu include:\r\nFerula narthex, Asafoetida, Devil\'s dung, Food of the God, Hing.', 'Hiṅgu (asafoetida) is a powerful spice and medicine widely used in Indian households.\r\nIt is also used for Severe gas, Abdominal pain, Colic disorders. It has properties like Strong carminative, Vāta-Kapha pacifier, Antispasmodic. It is one of the best remedies for digestive disorders and gas problems.', 'Ferula_assa-foetida.jpg'),
(7, 'Elaichi', 'Suksmaila', 'Elettaria cardamomum', 'Ela,Elaichi,cardamomum', 'Elaichi (cardamom) offers significant health benefits, including enhanced digestion, reduced blood pressure, and improved oral health. Rich in antioxidants and diuretic properties, it aids in reducing inflammation, fighting bad breath, and aiding respiratory health.', 'Elaichi.jpeg'),
(0, 'Kesara', 'Kesara', 'Crocus sativus', 'saffron crocus,Saffron,Kesar', 'Saffron helps in improving mood and reducing depression symptoms, supporting weight loss by reducing appetite, enhancing memory, treating PMS symptoms, and potentially protecting against age-related eye diseases.', 'Saffron.jpeg'),
(8, 'Kesara', 'Kesara', 'Crocus sativus', 'saffron crocus,Saffron,Kesar', 'Saffron helps in improving mood and reducing depression symptoms, supporting weight loss by reducing appetite, enhancing memory, treating PMS symptoms, and potentially protecting against age-related eye diseases.', 'Saffron.jpeg'),
(9, 'Tvak', 'Tvak', 'Cinnamomum zeylanicum', 'Dalchini ,cassia, canella ', 'Cinnamon helps combat oxidative stress and chronic inflammation, which reduces the risk of heart disease by lowering bad cholesterol (LDL) and triglycerides. Beyond metabolic support, cinnamon possesses antibacterial and antiviral properties that aid digestion, boost immunity, and may even support brain health by protecting against neurodegenerative conditions.', 'Cinnamon.jpeg'),
(10, 'Patra', 'Tamalapatra', 'Cinnamomum tamala', 'Malabar leaf, Indian cassia, Tejpatta.', 'Tamalapatra helps in aiding digestion, reducing inflammation, and managing blood sugar levels.', 'tamalapatra.jpeg'),
(11, 'Tuga', 'Tuga', 'Hibiscus abelmoschus', 'ambrette seed, musk mallow, musk okra, or muskdana', 'Musk seed promote heart health, boost immunity, improve digestion, strengthen bones, and support skin and hair health due to high antioxidant content', 'Musk seed.jpeg'),
(12, 'Dhanyaka', 'Dhanyaka', 'Coriandrum sativum', 'Coriander, Dhania', 'corainder helps to lower blood sugar, improved digestion, reduced inflammation, and enhanced heart health.', 'Coriander.jpeg'),
(13, 'Jiraka', 'Cuminum cyminum', 'Jiraka', 'cumin, jeera', 'cumin helps in promoting digestion, boosting immunity, and aiding weight management.', 'Jeera.jpeg'),
(14, 'Pippali', 'Pippali', 'Piper longum', 'Pipli, long pepper, Tippili', 'Pippali helps in improving digestion, supporting respiratory health, and increasing nutrient bio availability.', 'long pepper.jpeg'),
(15, 'Cavya', 'Cavya', 'Piper chaba', 'Chavya, Piper retrofractum Vahl, Piper chaba Hunter.', 'chavya helps in improves digestive health, metabolism, and immunity.', 'chavya.jpeg'),
(16, 'Citraka', 'Citraka', 'Plumbago zeylanica', 'Leadwort, Ceylon Leadwort, White Leadwort, Doctorbush.', 'Citraka helps to improve digestion, boost metabolism for weight loss, and manage chronic conditions like piles, arthritis, and skin disorders.', 'citraka.jpeg'),
(17, 'Nagara', 'Nagara', 'Zingiber officinale', 'Dry Ginger, Viśvabheṣaj, Viśva, Śṛṅgavera, Mahaushadha, Vishvaushadha, Rahuchatra, Katubhed, Katukandh', 'Nagara acts as a potent digestive aid, anti-inflammatory, and remedy for respiratory issues like coughs, cold, and bronchitis.', 'nagara.jpeg'),
(18, 'Marica', 'Marica', 'Piper nigrum', 'Kalimirch, Kali Mirchi, Golmirch, Gulmirch, Milagu, Nallumulku, Milaku, Kari, Miriyalu, Marichamu, Miriyalatige.', 'Marica helps in boosts nutrient absorption, aids digestion, and reduces inflammation.', 'Marica.jpeg'),
(19, 'Dipyaka', 'Dipyaka', 'Trachyspermum ammi', 'Ajwain seeds, Bishop\'s weed, Ajowan caraway, Celery seed, Yavānī, Ajamoda, Kharashva, Deepyaka, Bhrmakusha, Kharvi, and Ugragandhika.', 'Dipyaka aids in digestion, eases respiratory issues, and provides pain relief. It acts as a powerful antimicrobial agent, reduces bloating, relieves indigestion and acidity, eases joint pain, helps manage weight by boosting metabolism, and assists in managing respiratory conditions like asthma.', 'Ajwain.jpeg'),
(20, 'Amlavetasa', 'Amlavetasa', 'Garcinia cambogia', 'Malabar tamarind, Garcinia gummi-gutta, brindleberry, fish tamarind.', 'Malabar tamarind helps in supporting weight loss by suppressing appetite and blocking fat production and also acts as a digestive agent and sour agent.', 'malabar tamarind.jpeg'),
(21, 'Sandalwood', 'Candana', 'Santalum album', 'Chandan, Safed Chandan, Gandha, Sandanam, Chandanam, Srigandha, White Sandalwood, Sandal', 'Strong cooling effect (reduces body heat). Relieves burning sensation and fever. Improves skin (acne, pigmentation, rashes). Calms mind and reduces stress. Antiseptic and anti-inflammatory', 'chandana.jpeg'),
(22, 'Vetiver', 'Usīra', 'Vetiveria zizanioides', 'Khus, Khus-khus, Vettiveru, Vettiver, Ramacham, Lavancha, Vetiver root', 'Powerful body coolant. Relieves burning sensation and thirst. Useful in urinary disorders. Blood purifier. Reduces sweating and body odor', 'Vetiver.jpeg'),
(23, 'Indian Cedar', 'Tuni', 'Cedrela toona', 'Toon, Tun, Red cedar, Toona tree, Suren', 'Astringent (tightens tissues). Helps digestion. Anti-inflammatory. Useful in diarrhea and dysentery. Promotes wound healing', 'Cedrela toona.jpeg'),
(24, 'Agarwood', 'Aguru', 'Aquilaria agallocha', 'Oud, Agar, Eaglewood, Aloeswood', 'Calms mind and relieves stress. Improves digestion. Pain-relieving properties. Used in perfumes and rituals. Helps in respiratory disorders', 'agarwood.jpeg'),
(25, 'Turmeric', 'Haridrā', 'Curcuma longa', 'Haldi, Pasupu, Manjal, Arishina, Manjal, Indian saffron, Yellow root', 'Powerful anti-inflammatory. Blood purifier. Boosts immunity. Improves digestion. Heals wounds and skin diseases. Antioxidant and antimicrobial', 'turmeric.jpeg'),
(26, 'Camphor', 'Karpūra', 'Cinnamomum camphora', 'Kapoor, Karpooram, Karpura, Camphor crystal, Bhimseni kapoor', 'Relieves cough and cold. Acts as antiseptic and antimicrobial. Reduces itching and skin infections. Relieves headache. Improves blood circulation (external use)', 'camphor.jpeg'),
(27, 'Mace', 'Jātīpatrī', 'Myristica fragrans', 'Javitri, Japatri, Jathipathri, Mace spice, Nutmeg aril', 'Helps in diarrhea. Improves digestion. Relieves mouth disorders. Pain-relieving. Enhances appetite', 'mace.jpeg'),
(28, 'Nutmeg', 'Jātīphala', 'Myristica fragrans', 'Jaiphal, Jajikaya, Jathikkai, Jaajikaayi, Nutmeg seed', 'Promotes sleep (useful in insomnia). Improves digestion. Treats diarrhea. Strengthens nervous system. Reduces anxiety and stress', 'nutmeg.jpeg'),
(29, 'Chaste Tree', 'Harenu', 'Vitex agnus-castus', 'Chaste berry, Monk’s pepper, Nirgundi (related plant), Five-leaved chaste tree', 'Helps in digestion. Reduces inflammation. Useful in fever. Hormonal balance support. Supports reproductive health', 'Harenu.jpeg'),
(30, 'Indian Valerian', 'Tagara', 'Valeriana wallichii', 'Sugandh Bala, Tagaramu, Indian valerian root, Mushkbala', 'Treats insomnia. Reduces anxiety and stress. Calms nervous system. Pain-relieving. Useful in neurological disorders', 'Tagara.jpeg');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `alternate_email` varchar(100) DEFAULT NULL,
  `profile_pic` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `alternate_email`, `profile_pic`) VALUES
(0, 'vaisshnave', 'vaiss@gmail.com', '$2y$10$G/0Ao4l55jovDbENnmm72e50ZgE0sbq/bF7n.dms1jy6TKSca5dmK', NULL, NULL),
(0, 'vaisshnave', 'vaiss@gmail.com', '$2y$10$oQ1Vm9TQv6HgMc5tEIGcSOXr7DICrSlaOzCK7vixWbYbvPGGiY/J.', NULL, NULL),
(0, 'vais', 'vais@gmail.com', '$2y$10$HuF2tmjJucDWETPSjFmDUOEhTQkXBpVxKPCRQSbHTaSt/0VLPadvi', NULL, NULL),
(0, 'vais', 'vais@gmail.com', '$2y$10$l7BDRR28A6Vnz6LgCFf41OtaabAckjqHIHutHP9uO9RLnn.bNrGtq', NULL, NULL),
(0, 'vam', 'vam@gmail.com', '$2y$10$778GKjZ3LSeG2R72Afdp0.gwHVvY1J7O7NJP4ix0X1PveAVrb/y82', NULL, NULL),
(0, 'hmmm', 'hmmm@gmail.com', '$2y$10$FVPh9e9tXxjLLesI2oDZPO1K69e8ZjRh4ib5pzzvagHN3plP.r5gG', NULL, NULL),
(0, 'hmmm', 'hmmm@gmail.com', '$2y$10$o92LJQQfxjlz7.4FkPK1/uD8p4ar0FX0w/PxikhXlvRzKhSEiMFue', NULL, NULL),
(0, 'clio', 'clio@gmail.com', '$2y$10$vN.mmk0PBeTe6U3MRT2euODG6MsijE.eFUnq2uOFZ8TChorWb1Nz6', NULL, NULL),
(0, 'vaisshnave jannapureddy', 'jannapureddyvaisshnave@gmail.com', '$2y$10$KnAcNUAMa3nOvG8e5600rO84WXc3a7KiO1ulZXLAiCmwGKGgv7Yii', NULL, '133916191878423549.jpg'),
(0, 'hello', 'hello@gmail.com', '$2y$10$2P4nmTq7igcMIfhh6uQEued.zhGWVL9SlwsEPK.k3kiiSEAw8HrSe', NULL, NULL),
(0, 'home', 'home@gmail.com', '$2y$10$E2ZNmnKZI/w3Tv7zr3ACwOevrxWm6pVM6TfWYPXkWtCry.PbAWQpG', 'jannapureddyvaisshnave@gmail.com', '6a001218c1dd6.jpg');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
